# Generated by Django 6.0.2 on 2026-02-21 20:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import progress.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, validators=[progress.validators.validate_no_future_date])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1), progress.validators.validate_max_duration])),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Optional: Estimated calories burned', null=True, validators=[progress.validators.validate_max_calories])),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(help_text='Rate the workout (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workout')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
