# Generated by Django 6.0.2 on 2026-02-21 20:27

import django.core.validators
import django.db.models.deletion
import exercises.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[exercises.validators.validate_name_length])),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full', 'Full Body'), ('cardio', 'Cardio')], max_length=20)),
                ('equipment', models.CharField(choices=[('none', 'No Equipment'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell'), ('machine', 'Machine'), ('bands', 'Resistance Bands'), ('bodyweight', 'Bodyweight')], max_length=20)),
                ('sets', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), exercises.validators.validate_max_sets])),
                ('reps', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), exercises.validators.validate_max_reps])),
                ('rest_seconds', models.IntegerField(default=60, help_text='Resting time between sets in seconds', validators=[exercises.validators.validate_rest_time])),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
        ),
    ]
